import { Header } from "@/components/Header";
import { Toaster } from "@/repo/ui/components/ui/toaster";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <main>
                <Header setup />
                {children}
            </main>
            <Toaster />
        </>
    );
}
